config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    get 'meetings/index'
  end
  devise_for :users
  resources :books
  
  resources :clubs do
    scope module: :clubs do
      resources :memberships
      resources :recommendations
      resources :meetings
    end
  end
  resources :users do
    scope module: :users do 
      resources :clubs, only: %w[index destroy]
      resources :memberships, only: %w[index destroy]
      resources :recommendations
      resources :meetings, only: %w[index]
    end
  end

  get 'book_search', to: 'book_search#show'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/book_search_controller.rb
class BookSearchController < ApplicationController
  def show; end
end

app/views/book_search/new.html.erb
<div data-controller="book-search" data-reflex-root="#morph">
  <input type="text" placeholder="Search for a book..." class="form-control form-control-lg d-inline-block col-4"
    data-target="book-search.query" data-action="debounced:input->book-search#perform">
  <%= link_to("Add Book Manually", new_book_path) %>
  <div id="morph" class="mt-4">
    <span data-target="book-search.activity" class="text-danger" hidden>
      <i class="fas fa-spinner fa-spin"></i>
      Searching for books...
    </span>
    <span data-target="book-search.count" class="text-success">
      <strong><%= number_with_delimiter @books&.dig("num_found").to_i %></strong> books found
    </span>

    <table data-target="book-search.list" class="table mt-2" <%= "hidden" unless @books&.dig("docs").present? %>>
      <thead>
        <tr>
          <th scope="col">Subject</th>
          <th scope="col">Title</th>
          <th scope="col">Author</th>
          <th scope="col">Publish Date</th>
          <th scope="col">ISBN</th>
        </tr>
      </thead>
      <tbody>
        <% if @books&.dig("docs").present? %>
          <% @books["docs"][0,12].each do |book| %>
            <tr>
              <td><%= truncate book["subject"]&.join(", "), length: 30 %></th>
              <td><%= truncate book["title"], length: 30 %></th>
              <td><%= book["author_name"]&.join ", " %></td>
              <td><%= book["first_publish_year"] %></td>
              <td><%= book["isbn"]&.first %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/book_search/show.html.erb
<div data-controller="book-search" data-reflex-root="#morph">
  <input type="text" placeholder="Search for a book..." class="form-control form-control-lg d-inline-block col-4"
    data-target="book-search.query" data-action="debounced:input->book-search#perform">
  <%= link_to("Add Book Manually", new_book_path) %>
  <div id="morph" class="mt-4">
    <span data-target="book-search.activity" class="text-danger" hidden>
      <i class="fas fa-spinner fa-spin"></i>
      Searching for books...
    </span>
    <span data-target="book-search.count" class="text-success">
      <strong><%= number_with_delimiter @books&.dig("num_found").to_i %></strong> books found
    </span>

    <table data-target="book-search.list" class="table mt-2" <%= "hidden" unless @books&.dig("docs").present? %>>
      <thead>
        <tr>
          <th scope="col">Subject</th>
          <th scope="col">Title</th>
          <th scope="col">Author</th>
          <th scope="col">Publish Date</th>
          <th scope="col">ISBN</th>
        </tr>
      </thead>
      <tbody>
        <% if @books&.dig("docs").present? %>
          <% @books["docs"][0,12].each do |book| %>
            <tr>
              <td><%= truncate book["subject"]&.join(", "), length: 30 %></th>
              <td><%= truncate book["title"], length: 30 %></th>
              <td><%= book["author_name"]&.join ", " %></td>
              <td><%= book["first_publish_year"] %></td>
              <td><%= book["isbn"]&.first %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>