config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    get 'meetings/index'
  end
  devise_for :users
  resources :books
  
  resources :clubs do
    scope module: :clubs do
      resources :memberships
      resources :recommendations
      resources :meetings
    end
  end
  resources :users do
    scope module: :users do 
      resources :clubs, only: %w[index destroy]
      resources :memberships, only: %w[index destroy]
      resources :recommendations
      resources :meetings, only: %w[index]
    end
  end

  get 'book_search', to: 'book_search#show'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/club.rb
# == Schema Information
#
# Table name: clubs
#
#  id          :bigint           not null, primary key
#  description :text
#  founded     :date
#  invite_code :string
#  is_private  :boolean          default(FALSE)
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Club < ApplicationRecord
  # associations
  has_many :memberships
  has_many :users, through: :memberships
  has_many :recommendations
  has_many :meetings

  # Validations
  validates :name, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 50}
  validates :founded, presence: true
  validate :not_founded_in_the_future

  scope :public_clubs, -> { where(is_private: false) }

  def not_founded_in_the_future
    return if founded.nil?

    errors.add(:end_founded, "cannot be in the future") unless founded <= Time.now
  end
end

app/models/membership.rb
# == Schema Information
#
# Table name: memberships
#
#  id         :bigint           not null, primary key
#  role       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  club_id    :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_memberships_on_club_id  (club_id)
#  index_memberships_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (club_id => clubs.id)
#  fk_rails_...  (user_id => users.id)
#
class Membership < ApplicationRecord
  ROLE_TYPES = %w[admin moderator member].freeze
  enum role: ROLE_TYPES

  belongs_to :user
  belongs_to :club

  scope :admins, -> { where(role: 0) }
  scope :moderators, -> { where(role: 1) }
  scope :members,  -> { where(role: 2) }

  validates :role, presence: true
end

app/controllers/clubs/meetings_controller.rb
module Clubs
  class MeetingsController < ApplicationController
    before_action :set_club
    include Recommendable

    def index
      @meetings = @club.meetings
    end

    def show; end

    def new
      @meeting = Meeting.new
    end

    def create; end

    def edit; end

    def udpate; end

    def destroy; end

    private

    def set_club
      @club = Club.find(params[:club_id])
    end

    def recommendation_params
      params.require(:meeting).permit(:date, :club_id)
    end
  end
end

app/controllers/clubs/memberships_controller.rb
module Clubs
  class MembershipsController < ApplicationController
    before_action :set_book, only: %w[show edit update delete]
    before_action :set_club

    def index
      @memberships = Membership.includes([:user]).where(club: @club)
      # @memberships = @club.memberships
    end

    def show; end

    def new
      @membership = Membership.new
    end

    def create
      @membership = Membership.new(membership_params)

      if @membership.save
        redirect_to club_memberships_path(@club)
      else
        render :new
      end
    end

    def edit; end

    def update
      if @membership.update(membership_params)
        redirect_to club_memberships_path(@club)
      else
        render :edit
      end
    end

    def delete
      @membership.delete
      redirect_to user_path(@membership.user)
    end

    private

    def set_membership
      @membership = Membership.find(params[:id])
    end

    def set_club
      @club = Club.find(params[:club_id])
    end

    def membership_params
      params.require(:membership).permit(:role, :user_id, :club_id)
    end
  end
end

app/controllers/clubs/recommendations_controller.rb
module Clubs
  class RecommendationsController < ApplicationController
    before_action :set_club
    include Recommendable

    def index
      @recommendations = Recommendation.includes([:book]).where(club: @club)
    end

    def create
      @recommendation = Recommendation.create(recommendation_params)

      respond_to do |format|
        if @recommendation.save
          format.html { redirect_to [@club, @recommendation], notice: "Recommendation was successfully created." }
          format.json { render :show, status: :created, location: @recommendation }
        else
          format.html { render :new }
          format.json { render json: @recommendation.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @recommendation.update(recommendation_params)
          format.html { redirect_to @recommendation, notice: "recommendation was successfully updated." }
          format.json { render :show, status: :ok, location: @recommendation }
        else
          format.html { render :edit }
          format.json { render json: @recommendation.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @recommendation.destroy

      respond_to do |format|
        format.html { redirect_to [@club, :recommendations], notice: "Recommendation was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private

    def set_club
      @club = Club.find(params[:club_id])
    end
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: %w[show edit update destroy]

  def index
    # TODO: add pagination
    @clubs = Club.public_clubs
  end

  def show; end

  def new
    @club = Club.new
  end

  def create
    @club = Club.create(club_params)

    respond_to do |format|
      if @club.save
        format.html { redirect_to @club, notice: "Club was successfully created." }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: "Club was successfully updated." }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @club.destroy

    respond_to do |format|
      format.html { redirect_to clubs_url, notice: "Club was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_club
    @club = Club.find(params[:id])
  end

  def club_params
    # TODO: Add permitable params
    params.require(:club).permit(:name, :founded, :description)
  end
end

app/helpers/club/meetings_helper.rb
module Club
  module MeetingsHelper
  end
end

app/helpers/clubs/meetings_helper.rb
module Clubs
  module MeetingsHelper
  end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/clubs/memberships/create.html.erb
<h1>Memberships#create</h1>
<p>Find me in app/views/memberships/create.html.erb</p>

app/views/clubs/memberships/delete.html.erb
<h1>Memberships#delete</h1>
<p>Find me in app/views/memberships/delete.html.erb</p>

app/views/clubs/memberships/edit.html.erb
<h1>Memberships#edit</h1>
<p>Find me in app/views/memberships/edit.html.erb</p>

app/views/clubs/memberships/index.html.erb
<h1>Memberships#index</h1>
<p>Find me in app/views/memberships/index.html.erb</p>
<ul>
  <%- @memberships.each do |m| %>
    <li><%= m.user.name %> - role: <%= m.role %></li>
  <% end %>
</ul>

app/views/clubs/memberships/new.html.erb
<h1>Join <%= @club.name %></h1>
<p>You are about to join the club, this will allow you to make recommendations, see meeting dates, and start converstations.</p>

<%= form_for [@club, @membership], remote: false do |f| %>
  <div class="field">
    <%= f.hidden_field :role, value: "member" %>
    <%= f.hidden_field :user_id, value: 1 %>
    <%= f.hidden_field :club_id, value: @club.id %>
    <%= f.submit("Join Club") %>
    <%= link_to("Cancel", clubs_path) %>
  </div>
    
<% end %>

<div style='width: 3rem; height: 3rem; border-radius: 100%;'>
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" class="avatar" aria-hidden="true">
      <defs>
        <clipPath id="porthole">
          <circle cx="50%" cy="50%" r="50%"/>
        </clipPath>
      </defs>

      <g>
        <rect width="100%" height="100%" rx="250" fill="#F95C5C"/>

        <text x="50%" y="50%" fill="#000000" text-anchor="middle" dy="0.35em" textLength="80%" lengthAdjust="spacingAndGlyphs" font-family="-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif" font-size="230" font-weight="800" letter-spacing="-5">
          <%= User.first.name.initials %>
        </text>
      </g>
    </svg>

</div>

app/views/clubs/memberships/update.html.erb
<h1>Memberships#update</h1>
<p>Find me in app/views/memberships/update.html.erb</p>